language: c

script:
  - ./bootstrap.sh
  - ./configure CPPFLAGS="-I/usr/include/geotiff"
  - make
  - sudo make install

matrix:
  include:
    - os: linux
      name: "Ubuntu 14.04 full-featured with GraphicsMagick"
      addons:
        apt:
          packages:
            - graphicsmagick
            - libmotif-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - libproj-dev
            - libdb5.3-dev
            - libax25-dev
            - shapelib
            - libshp-dev
            - festival
            - festival-dev
            - libgeotiff-dev
            - libgraphicsmagick1-dev
            - gpsman
            - gpsmanshp
    - os: linux
      dist: xenial
      name: "Ubuntu 16.04 full-featured with GraphicsMagick"
      addons:
        apt:
          packages:
            - graphicsmagick
            - libmotif-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - libproj-dev
            - libdb5.3-dev
            - libax25-dev
            - shapelib
            - libshp-dev
            - festival
            - festival-dev
            - libgeotiff-dev
            - libgraphicsmagick1-dev
            - gpsman
            - gpsmanshp
    - os: linux
      name: "Ubuntu 14.04 light with ImageMagick"
      addons:
        apt:
          packages:
            - imagemagick
            - libmotif-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - libdb5.3-dev
            - shapelib
            - libshp-dev
            - libmagickcore-dev
    - os: osx
      name: "OSX"
      addons:
        homebrew:
          packages:
            - berkeley-db
            - graphicsmagick
            - libgeotiff
            - openmotif
            - pcre
            - proj
            - shapelib
            - wget
