language: c

script:
  - ./bootstrap.sh
  - ./configure CPPFLAGS="-I/usr/include/geotiff"
  - make
  - sudo make install

matrix:

  exclude:
    - compiler: gcc

  include:

    - os: linux
      dist: xenial
      name: "Ubuntu 16.04 light w/ImageMagick"
      env:
        - MAGIC_BIN="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Magick-config"
      addons:
        apt:
          packages:
            - imagemagick
            - libmotif-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - libdb5.3-dev
            - shapelib
            - libshp-dev
            - libmagickcore-dev

    - os: linux
      dist: xenial
      name: "Ubuntu 16.04 gcc8 full-featured w/GraphicsMagick"
      install:
        # Can't use "env:" for the CC variable: It gets overwritten by Travis-CI
        - export CC="gcc-8" CFLAGS="${CFLAGS} -Wno-format-truncation -Wno-stringop-truncation"
        - echo ${CC}
        - ${CC} --version
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - graphicsmagick
            - libmotif-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - libproj-dev
            - libdb5.3-dev
            - libax25-dev
            - shapelib
            - libshp-dev
            - festival
            - festival-dev
            - libgeotiff-dev
            - libgraphicsmagick1-dev
            - gpsman
            - gpsmanshp
            - libwebp-dev

    - os: osx
      name: "OSX semi-light w/GraphicsMagick"
      addons:
        homebrew:
          packages:
            - berkeley-db
            - graphicsmagick
            - libgeotiff
            - openmotif
            - pcre
            - proj
            - shapelib
            - wget


